# Generated by Django 3.0.2 on 2020-02-23 19:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=0, max_digits=8)),
                ('ingresos', models.IntegerField()),
                ('gastos', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='creation_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 14, 50, 39, 385311)),
        ),
        migrations.AlterField(
            model_name='account',
            name='state_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.StateAccount'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.TypeAccount'),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.Balance'),
        ),
    ]
