# Generated by Django 3.0.2 on 2020-02-23 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20200223_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='creation_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 14, 57, 14, 443246)),
        ),
    ]
