# Generated by Django 3.0.2 on 2020-03-01 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_auto_20200223_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='creation_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 15, 26, 7, 34376)),
        ),
        migrations.AlterField(
            model_name='balance',
            name='id_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Account'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], default='Gasto', max_length=10)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=8)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Categoria')),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Account')),
                ('id_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Balance')),
            ],
        ),
    ]
