# Generated by Django 3.0.2 on 2020-03-08 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_auto_20200301_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='creation_day',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 15, 15, 7, 164742)),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.ExpenseType'),
        ),
    ]
